### ISSUE TITLE
Integrate with Rules API

### ISSUE THREAD

**Issue by jessicalins** [observatorium/thanos-rule-syncer#2]
As mentioned https://observatorium.io/docs/proposals/20201019-prometheus-rules-in-observatorium-api.md/#2-sync-rules-to-rule, after `thanos-rule-syncer` gets data from observatorium/Rules API, it needs to:

* combine the data into one file that it's shared with Thanos Rule
* calls Thanos Rule's `/reload` endpoint to reload the config
* Thanos Rule then starts to evaluate the recording/alerting rules and stores the results in a local TSDB instance

**Comment by squat** [comment]
Fixed by https://github.com/observatorium/thanos-rule-syncer/pull/3
