### ISSUE TITLE
Add support for multiple tenants

### ISSUE THREAD

**Issue by onprem** [observatorium/thanos-rule-syncer#7]
### Problem

Thanos Rule Syncer currently supports fetching rules for a single tenant from Observatorium API. This means that if you are running Obs API with multiple tenants (almost always), you'd need to run one Thanos Rule Syncer sidecar for each tenant.

### Proposed Solution

We can add support for specifying multiple tenants and their credentials as input to Rule Syncer (maybe as a yaml file) and then we can fetch rules for all of them, combine in a single file, and then follow the same pattern we followed for a single tenant.

**Comment by squat** [comment]
Yes indeed this was the original vision of the rule-syncer, that you would run one sidecar per tenant.
However, it would indeed be trivial to add support for multiple tenants. I think that having a yaml file to configure this tiny app is a bit overkill, however, we need to configure not just a list of tenants but also a new set of credentials for each tenant, as they may all use different OIDC providers.

**Comment by onprem** [comment]
> however, we need to configure not just a list of tenants but also a new set of credentials for each tenant, as they may all use different OIDC providers.

Yep, this is why I was thinking of a yaml file. Repeated flags feels a bit more confusing from user perspective.

**Comment by onprem** [comment]
We decided to use the `listAllRules` endpoint of Rules Backend directly (#9). This means we don't need multi-tenant support if its used inside an Observatorium deployment.
